[build]
  publish = "dist"
  command = "npm ci --include=dev && npx vite build"
  environment = { NODE_VERSION = "20", NPM_CONFIG_PRODUCTION = "false" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
