services:
  - type: web
    name: updates-admin
    env: static
    buildCommand: ./build.sh
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
